
RUN_CONFIG:
  pipeline_name: __default__
  only_missing: True
  runner: SequentialRunner # None
  tags: # None
  node_names: # None
  from_nodes: # None
  to_nodes: # None
  from_inputs: # None
  load_versions: # None

MLFLOW_LOGGING_CONFIG:
  offset_hours: 0
  logging_artifacts:  # None
  
PIPELINES:
  __default__:
    =: pipelinex.FlexiblePipeline
    parameters_in_inputs: False
    module:  # None
    decorator: pipelinex.log_time
    nodes:

      - inputs: parameters
        func: demo.voc_demo.generate_datasets
        outputs:
          - train_dataset
          - val_dataset

      - inputs: train_dataset
        func: {=: pipelinex.GetPartialDataset, size: 100}
        outputs: partial_train_dataset

      - inputs: val_dataset
        func: {=: pipelinex.GetPartialDataset, size: 100}
        outputs: partial_val_dataset
